---

- name: DBserver setup
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla

  tasks:
    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Install pymysql
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Start and enable mariadb
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
